/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 30 09:13:23 GMT 2019
 */

package com.test.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.test.util.LamdaExpression;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LamdaExpression_ESTest extends LamdaExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaAdd(0, 805);
      assertEquals(805.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaMultiply(2416, 0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaMultiply(1682, (-570));
      assertEquals((-958740.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaAdd(0, 0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambaSquareFunc(0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      lamdaExpression0.LambaExpForAL();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaAdd((-2201), (-2201));
      assertEquals((-4402.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambdaMultiply((-2201), (-2201));
      assertEquals(4844401.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LamdaExpression lamdaExpression0 = new LamdaExpression();
      double double0 = lamdaExpression0.LambaSquareFunc((-2201));
      assertEquals(4844401.0, double0, 0.01);
  }
}
